# Generated by Django 5.0.1 on 2024-02-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('user_name', models.CharField(max_length=25)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
