# Generated by Django 5.0.1 on 2024-02-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='user_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
