# Generated by Django 5.0.1 on 2024-02-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
