# Generated by Django 5.0.1 on 2024-02-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_remove_hotels_user_customuser_hotels_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='admin',
        ),
        migrations.DeleteModel(
            name='Customuser',
        ),
    ]
