# Generated by Django 5.0.2 on 2024-03-03 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_customer_district_remove_customer_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("room_number", models.IntegerField(primary_key=True, serialize=False)),
                ("capacity", models.SmallIntegerField()),
                ("number_of_beds", models.SmallIntegerField()),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("King", "King"),
                            ("Luxury", "Luxury"),
                            ("Normal", "Normal"),
                            ("Economic", "Economic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.FloatField()),
                ("floor_number", models.IntegerField()),
                ("photo", models.ImageField(blank=True, null=True, upload_to="media")),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.hotel"
                    ),
                ),
            ],
        ),
    ]
