# Generated by Django 5.0.2 on 2024-03-05 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_deleted",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Facilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, max_length=20)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="media")),
                ("is_deleted", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.hotel"
                    ),
                ),
            ],
        ),
    ]
