# Generated by Django 5.0.2 on 2024-03-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_room_is_deleted_facilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="facilities",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
