# Generated by Django 5.0.2 on 2024-03-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_customer_is_deleted_hotel_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="hotel_number",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
