# Generated by Django 5.0.2 on 2024-03-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_rename_phone_customer_phones"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="phones",
            new_name="phone",
        ),
    ]
