# Generated by Django 5.0.2 on 2024-03-14 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_booking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="chech_in",
            new_name="check_in",
        ),
    ]
