# Generated by Django 5.0.2 on 2024-03-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
