# Generated by Django 5.0.2 on 2024-03-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_number',
        ),
    ]
