# Generated by Django 5.0.2 on 2024-04-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_hotel_hotel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='room_id',
            field=models.IntegerField(max_length=8),
        ),
    ]
