# Generated by Django 5.0.2 on 2024-04-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_booking_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cost',
            field=models.IntegerField(default=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='room_id',
            field=models.IntegerField(),
        ),
    ]
