# Generated by Django 5.0.2 on 2024-04-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_booking_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cost',
            field=models.IntegerField(default=230),
            preserve_default=False,
        ),
    ]
